/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DbFinalProject;

import javax.swing.JOptionPane;

/**
 *
 * @author Umaima Tariq
 */
public class SignUpLast extends javax.swing.JFrame
{

    /**
     * Creates new form SignUpLast
     */
    public SignUpLast()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tcpass = new javax.swing.JPasswordField();
        tun = new javax.swing.JTextField();
        tph = new javax.swing.JTextField();
        un = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        cpass = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        openservices = new javax.swing.JButton();
        tpass = new javax.swing.JPasswordField();
        fn = new javax.swing.JLabel();
        tfn = new javax.swing.JTextField();
        ln = new javax.swing.JLabel();
        tln = new javax.swing.JTextField();
        add = new javax.swing.JLabel();
        tadd = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        account = new javax.swing.JLabel();
        cross = new javax.swing.JLabel();
        plumb = new javax.swing.JCheckBox();
        cus = new javax.swing.JCheckBox();
        cyc = new javax.swing.JLabel();
        elect = new javax.swing.JCheckBox();
        paint = new javax.swing.JCheckBox();
        clean = new javax.swing.JCheckBox();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(28, 125, 211), 6));

        tcpass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tun.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tun.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                tunFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                tunFocusLost(evt);
            }
        });

        tph.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        un.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        un.setText("Username");

        phone.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        phone.setText("Phone");

        cpass.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        cpass.setText("Confirm Password");

        pass.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        pass.setText("Password");

        openservices.setBackground(new java.awt.Color(255, 255, 255));
        openservices.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        openservices.setText("Sign UP");
        openservices.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        openservices.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                openservicesActionPerformed(evt);
            }
        });

        tpass.setBorder(new javax.swing.border.MatteBorder(null));

        fn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fn.setText("First Name");

        tfn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ln.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ln.setText("Last Name");

        tln.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        add.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add.setText("Address");

        tadd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel4.setBackground(new java.awt.Color(28, 125, 211));

        account.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        account.setText("Create Your Account");

        cross.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        cross.setText("X");
        cross.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                crossMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cross, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(account)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(cross, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 17, Short.MAX_VALUE)
                    .addComponent(account)
                    .addGap(0, 17, Short.MAX_VALUE)))
        );

        plumb.setBackground(new java.awt.Color(255, 255, 255));
        plumb.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        plumb.setText("Plumber");

        cus.setBackground(new java.awt.Color(255, 255, 255));
        cus.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        cus.setText("Customer");
        cus.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cusActionPerformed(evt);
            }
        });

        cyc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cyc.setText("Choose Your Category");

        elect.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        elect.setText("Electrician");

        paint.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        paint.setText("Painter");

        clean.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        clean.setText("Cleaner");
        clean.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cleanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fn)
                                            .addComponent(ln)))
                                    .addComponent(un, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(96, 96, 96))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(phone)
                                    .addComponent(cpass, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(69, 69, 69))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tln)
                    .addComponent(tfn)
                    .addComponent(tun)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tpass, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(tph, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(tcpass, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(tadd, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(39, 39, 39))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cyc)
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cus)
                                .addGap(18, 18, 18)
                                .addComponent(plumb)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(elect)
                                .addGap(18, 18, 18)
                                .addComponent(paint)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(clean)
                                .addGap(0, 23, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(openservices, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(236, 236, 236))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fn)
                    .addComponent(tfn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ln)
                    .addComponent(tln, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tun, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(un, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tph, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tpass, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tcpass, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpass, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add)
                    .addComponent(tadd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cus)
                    .addComponent(plumb)
                    .addComponent(cyc))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(elect)
                    .addComponent(paint)
                    .addComponent(clean))
                .addGap(77, 77, 77)
                .addComponent(openservices, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crossMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_crossMouseClicked
    {//GEN-HEADEREND:event_crossMouseClicked
System.exit(0);
    }//GEN-LAST:event_crossMouseClicked

    private void cusActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cusActionPerformed
    {//GEN-HEADEREND:event_cusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cusActionPerformed

    private void cleanActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cleanActionPerformed
    {//GEN-HEADEREND:event_cleanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cleanActionPerformed

    private void tunFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_tunFocusGained
    {//GEN-HEADEREND:event_tunFocusGained
 if(tun.getText().trim().toLowerCase().equals("username"))
        {
            tun.setText("");
           
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tunFocusGained

    private void tunFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_tunFocusLost
    {//GEN-HEADEREND:event_tunFocusLost
if(tun.getText().trim().equals("") || 
          tun.getText().trim().toLowerCase().equals("username"))
        {
            tun.setText("username");
         
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tunFocusLost

    private void openservicesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_openservicesActionPerformed
    {//GEN-HEADEREND:event_openservicesActionPerformed

        //get data from fields
        String fname = tfn.getText();
String lname = tln.getText();
         String username = tun.getText();
         String pass1 = String.valueOf(tpass.getPassword());
         String pass2 = String.valueOf(tcpass.getPassword());
         String phone = tph.getText();
         String category = "customer";
         
         if(plumb.isSelected()){
             category = "plumber";}
             else if(clean.isSelected())
             {
             category = "cleaning"; }
             else if (paint.isSelected()){
             category = "plainting";}
             else if(elect.isSelected()){
             category = "electrician";}
             else if (cus.isSelected()){
             category = "Customer";


// TODO add your handling code here:
    }//GEN-LAST:event_openservicesActionPerformed
// create a function to verify the empty fields  
    

    }
    public boolean verifyFields()
    {
        String fname = tfn.getText();
        String lname = tln.getText();
        String uname = tun.getText();
        String phone1 = tph.getText();
        String pass1 = String.valueOf(tpass.getPassword());
        String pass2 = String.valueOf(tcpass.getPassword());
        if(fname.trim().equals("") || uname.trim().equals("") || phone1.trim().equals("")
           || pass1.trim().equals("") || pass2.trim().equals(""))
        {
            JOptionPane.showMessageDialog(null, "One Or More Fields Are Empty","Empty Fields",2);
            return false;
        }
        
        // check if the two password are equals or not
        else if(!pass1.equals(pass2))
        {
           JOptionPane.showMessageDialog(null, "Password Doesn't Match","Confirm Password",2); 
           return false;
        }
        
        // if everything is ok
        else{
            return true;
        }}
      // create a function to check if the entered username already exists in the database
   
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(SignUpLast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(SignUpLast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(SignUpLast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(SignUpLast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new SignUpLast().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel account;
    private javax.swing.JLabel add;
    private javax.swing.JCheckBox clean;
    private javax.swing.JLabel cpass;
    private javax.swing.JLabel cross;
    private javax.swing.JCheckBox cus;
    private javax.swing.JLabel cyc;
    private javax.swing.JCheckBox elect;
    private javax.swing.JLabel fn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel ln;
    private javax.swing.JButton openservices;
    private javax.swing.JCheckBox paint;
    private javax.swing.JLabel pass;
    private javax.swing.JLabel phone;
    private javax.swing.JCheckBox plumb;
    private javax.swing.JTextField tadd;
    private javax.swing.JPasswordField tcpass;
    private javax.swing.JTextField tfn;
    private javax.swing.JTextField tln;
    private javax.swing.JPasswordField tpass;
    private javax.swing.JTextField tph;
    private javax.swing.JTextField tun;
    private javax.swing.JLabel un;
    // End of variables declaration//GEN-END:variables
}
