/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DbFinalProject;
import javax.swing.*;
import java.awt.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Umaima Tariq
 */
public class SignInLast extends javax.swing.JFrame
{

    /**
     * Creates new form SignInLast
     */
    public SignInLast()
    {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtext = new javax.swing.JPanel();
        password = new javax.swing.JPasswordField();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        mainheading = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        signup1 = new javax.swing.JButton();
        signin = new javax.swing.JButton();
        u = new javax.swing.JTextField();
        Username = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 118, 222), 4));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 1, 29)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(28, 125, 211));
        jLabel3.setText("HouseHold Services");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel3)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel3)
                .addContainerGap(305, Short.MAX_VALUE))
        );

        jtext.setBackground(new java.awt.Color(255, 255, 255));
        jtext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 118, 222), 4));
        jtext.setForeground(new java.awt.Color(33, 118, 222));
        jtext.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                jtextFocusGained(evt);
            }
        });

        password.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        password.setForeground(new java.awt.Color(33, 118, 222));
        password.setBorder(null);
        password.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                passwordFocusLost(evt);
            }
        });

        jSeparator7.setBackground(new java.awt.Color(33, 118, 222));
        jSeparator7.setForeground(new java.awt.Color(33, 118, 222));
        jSeparator7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        jSeparator8.setBackground(new java.awt.Color(33, 118, 222));
        jSeparator8.setForeground(new java.awt.Color(33, 118, 222));

        mainheading.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        mainheading.setForeground(new java.awt.Color(33, 118, 222));
        mainheading.setText("Login to your Account");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setText("X");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLabel10MouseClicked(evt);
            }
        });

        signup1.setBackground(new java.awt.Color(33, 118, 222));
        signup1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        signup1.setForeground(new java.awt.Color(33, 118, 222));
        signup1.setText("Sign Up");
        signup1.setBorder(null);
        signup1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                signup1ActionPerformed(evt);
            }
        });

        signin.setBackground(new java.awt.Color(33, 118, 222));
        signin.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        signin.setForeground(new java.awt.Color(33, 118, 222));
        signin.setText("Sign In");
        signin.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                signinActionPerformed(evt);
            }
        });

        u.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        u.setForeground(new java.awt.Color(33, 118, 222));
        u.setBorder(null);
        u.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                uFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                uFocusLost(evt);
            }
        });
        u.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                uActionPerformed(evt);
            }
        });

        Username.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Username.setForeground(new java.awt.Color(33, 118, 222));
        Username.setText("Username");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setText("-");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jtextLayout = new javax.swing.GroupLayout(jtext);
        jtext.setLayout(jtextLayout);
        jtextLayout.setHorizontalGroup(
            jtextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jtextLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(signin, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(signup1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(jtextLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jtextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator8)
                    .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(u, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jtextLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jtextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainheading, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jtextLayout.setVerticalGroup(
            jtextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jtextLayout.createSequentialGroup()
                .addGroup(jtextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jtextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jtextLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(mainheading, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Username)
                .addGap(3, 3, 3)
                .addComponent(u, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jtextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signup1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jtext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jtext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtextFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jtextFocusGained
    {//GEN-HEADEREND:event_jtextFocusGained
        // TODO add your handling code here:
        

    }//GEN-LAST:event_jtextFocusGained

    private void signinActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_signinActionPerformed
    {//GEN-HEADEREND:event_signinActionPerformed
PreparedStatement st;
        ResultSet rs;
        
        // get the username & password
        String username = u.getText();
        String password1 = String.valueOf( password.getPassword());
        
        //create a select query to check if the username and the password exist in the database
        String query = "SELECT * FROM `users` WHERE `username` = ? AND `password` = ?";
        
        // show a message if the username or the password fields are empty
        if(username.trim().equals("username"))
        {
            JOptionPane.showMessageDialog(null, "Enter Your Username", "Empty Username", 2);
        }
        else if(password1.trim().equals("password"))
        {
            JOptionPane.showMessageDialog(null, "Enter Your Password", "Empty Password", 2);
        }
        else{
            
            try {
            st = BbmainClass.getConnection.prepareStatement(query);
            
            st.setString(1, username);
            st.setString(2, password1);
            rs = st.executeQuery();
            
            if(rs.next())
            {
                // show a new form
                SignInLast form = new  SignInLast();
                form.setVisible(true);
                form.pack();
                form.setLocationRelativeTo(null);
                // close the current form(login form)
                this.dispose();
                
            }else{
                // error message
                JOptionPane.showMessageDialog(null, "Invalid Username / Password","Login Error",2);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(  SignInLast.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        }
        
                                                       // TODO add your handling code here:
        

    }//GEN-LAST:event_signinActionPerformed

    private void signup1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_signup1ActionPerformed
    {//GEN-HEADEREND:event_signup1ActionPerformed
new SignUpLast().setVisible(true); 
this.dispose();
// TODO add your handling code here:
        
    }//GEN-LAST:event_signup1ActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabel10MouseClicked
    {//GEN-HEADEREND:event_jLabel10MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void passwordFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_passwordFocusGained
    {//GEN-HEADEREND:event_passwordFocusGained
String pass = String.valueOf(password.getPassword());
        
        if(pass.trim().toLowerCase().equals("password"))
        {
            password.setText("");
            password.setForeground(Color.black);
        }
        // set a yellow border to the jlabel icon
        
    }//GEN-LAST:event_passwordFocusGained

    private void uActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_uActionPerformed
    {//GEN-HEADEREND:event_uActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uActionPerformed

    private void uFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_uFocusGained
    {//GEN-HEADEREND:event_uFocusGained
u.setText("");         // TODO add your handling code here:
    }//GEN-LAST:event_uFocusGained

    private void uFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_uFocusLost
    {//GEN-HEADEREND:event_uFocusLost
 if(u.getText().trim().equals("") || 
           u.getText().trim().toLowerCase().equals("username"))
        {
            u.setText("username");
            u.setForeground(new Color(153,153,153));
        }        // TODO add your handling code here:
    }//GEN-LAST:event_uFocusLost

    private void passwordFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_passwordFocusLost
    {//GEN-HEADEREND:event_passwordFocusLost
  // if the password field is equal to password or empty
        // we will set the "password" text in the field 
        // on focus lost event
        
        // get the password text
        String pass = String.valueOf(password.getPassword());
        
        if(pass.trim().equals("") || 
           pass.trim().toLowerCase().equals("password"))
        {
            password.setText("password");
            password.setForeground(new Color(153,153,153));
        }        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFocusLost

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabel1MouseClicked
    {//GEN-HEADEREND:event_jLabel1MouseClicked
                                            
        this.setState(JFrame.ICONIFIED);
        
                    // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

  
    public static void main(String args[])
    {
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(SignInLast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(SignInLast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(SignInLast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(SignInLast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new SignInLast().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JPanel jtext;
    private javax.swing.JLabel mainheading;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton signin;
    private javax.swing.JButton signup1;
    private javax.swing.JTextField u;
    // End of variables declaration//GEN-END:variables
}
